### ISSUE TITLE
Kernel dies while fitting the full model

### ISSUE THREAD

**Issue by Aexolowski** [dattalab/keypoint-moseq#15]
I am running the code on a jupyter notebook, and the Kernel keeps dying at the step of full model fitting. My PC and GPU should be powerful enough for that (256 GB RAM and the Nvidia Geforce RTX 3080), so I am not sure what the issue is.

**Comment by calebweinreb** [comment]
Hello! We're aware of this problem and trying to figure out what's going on. So far it seems like a windows-specific issue. Are you using Windows? 

Because the problem is OS specific, it's been hard to debug on our end. Would you be willing to update keypoint-moseq and jax-moseq as shown below? These versions are configured to print progress messages during model fitting so we can find out which step kills the kernel (make sure the keypoint MoSeq config has verbose set to True).
```
pip install -U git+https://github.com/dattalab/jax-moseq
pip install -U git+https://github.com/dattalab/keypoint-moseq.git@dev
```

**Comment by calebweinreb** [comment]
Great! The `apply_model` step isn't strictly required (unless you want to apply an existing model to new data). It mostly serves to prevent discontinuities caused by breaking up each session into chunks for parallelization. But these discontinuities are very rare (one per 10,000 frames by default). So for now, I would recommend running with `num_iters=0`, which will stitch the chunks back together while leaving the discontinuities. The full command would be:
```
results = kpms.apply_model(coordinates=coordinates, confidences=confidences, 
                           project_dir=project_dir, **config(), **checkpoint, num_iters=0)
```
If you're comfortable, it would be helpful if you shared the data (checkpoint file, config and keypoint data) so I can try to debug this on one of our windows machines. You could just send to my email (calebsw@gmail.com)

**Comment by calebweinreb** [comment]
There's now a section in the docs for dealing with a dead kernel
https://keypoint-moseq.readthedocs.io/en/latest/troubleshooting.html
