### ISSUE TITLE
Issue with grid movies

### ISSUE THREAD

**Issue by banchan86** [dattalab/keypoint-moseq#37]
Hi caleb, we are running into an issue with the grid movies being really cropped and not showing any of the keypoints or the full frame
![image](https://user-images.githubusercontent.com/28827340/236634077-8759f4cd-5b22-483f-8f54-19e0b6baf8cb.png)
but crowd movies look fine
![image](https://user-images.githubusercontent.com/28827340/236634108-b593cd55-8507-47b9-8c68-e70a61724c7c.png)

We are running kp.moseq 0.1.0 on faces of headfixed animals  (the same dataset i have been posting about this is Shawn from the stowers lab btw just switching to my own github account  :) )

**Comment by calebweinreb** [comment]
You can use the `window_size` parameter to increase the window for grid movies. E.g. if your videos are 640px by 480px, you could use `window_size=640` or something.
```
kpms.generate_grid_movies(name=name, project_dir=project_dir, **config(), window_size=640)
```

**Comment by calebweinreb** [comment]
Hmm that seems like a very drastic solution! I can just add a downscaling option to the grid movie function... in fact I just did. In the new grid movies function, the window size is set automatically based on the size of the animal (so hopefully you no longer have to set it explicitly). I also added a `max_video_size` parameter that will limit the total size of the grid movies by downscaling the videos if necessary. You can use the new function by installing the dev branch:
```
pip install -U git+https://github.com/dattalab/keypoint-moseq@dev
```
Note that because of some other changes in the dev branch, the data-loading functions now output a list of bodyparts. So you will have to update those lines to avoid getting an error:
```
# if you're using dlc
coordinates, confidences, bodyparts = kpms.load_deeplabcut_results(dlc_results)

# if using sleap
coordinates, confidences, bodyparts = kpms.load_sleap_results(sleap_results)
```
Give it a try and let me know how it goes!

**Comment by calebweinreb** [comment]
Awesome! will update the dependencies
