### ISSUE TITLE
Jaxlib CPU issues 

### ISSUE THREAD

**Issue by juliagorman** [dattalab/keypoint-moseq#5]
I am running off my Mac laptop and I installed pip as such: pip install "jax[cpu]" and now I am getting this error just when running the first line of the keypoint-MoSeq walkthrough 

<img width="494" alt="Screenshot 2023-03-22 at 11 58 59 AM" src="https://user-images.githubusercontent.com/32439305/227009419-378ecf77-1534-4a3e-8dba-1b0b2db5e184.png">

**Comment by calebweinreb** [comment]
The error

```
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

is caused by trying to pip install jax on a mac with an M1 chip. You can see a discussion about workarounds [here](https://github.com/google/jax/issues/5501). Basically, the two approaches seem to be installing jax with conda (from conda-forge) or installing jax via miniforge. 

I haven't been able to test either approach since I don't have an M1 chip... Would you be able to try the following and let me know how it goes? 

1. Delete your existing `keypoint_moseq` environment (`conda env remove -n keypoint_moseq`)
2. Reinstall using the conda .yml file from the repo, as described in the [keypoint-moseq docs](https://dattalab.github.io/moseq2-website/readthedocs/keypoint-moseq/install.html#install-using-conda)

**Comment by talmo** [comment]
I think PR #6 fixes the installation issues with the conda environment, and I was able to install it on CPU on an M1 Mac via the Linux CPU conda file (`conda_envs/environment.linux_cpu.yml`), but there are still other dependency issues.

I submitted PR #7 to add a Mac-specific conda environment file to fix this, but it only supports CPU.

For native Apple Silicon Metal support, see this related Jax issue: https://github.com/google/jax/issues/8074

**Comment by calebweinreb** [comment]
OK so final answer here is to install via conda
```
conda env create -f conda_envs/environment.mac_cpu.yml
```

**Comment by juliagorman** [comment]
when i run this command now, i get this error
<img width="761" alt="Screenshot 2023-04-18 at 2 23 46 PM" src="https://user-images.githubusercontent.com/32439305/233161515-26a81487-a2e0-43a4-9c18-0ddfeb7ce091.png">

**Comment by calebweinreb** [comment]
make sure the current working directory for your terminal is `keypoint-moseq`, i.e. by cloning the repo [as described in the docs](https://keypoint-moseq.readthedocs.io/en/latest/install.html#install-using-conda). 

```
git clone https://github.com/dattalab/keypoint-moseq
chdir keypoint-moseq
```
